using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace reromanlee.ReactiveLocalizer.CldrGenerator
{
    /// <summary>
    /// Builds generated C# files: always LF line endings and ASCII only, so the output is byte-identical on every
    /// machine and every character a reviewer can't see is spelled out as an escape.
    /// </summary>
    internal sealed class SourceText
    {
        private const char Backslash = (char)92;

        private readonly StringBuilder _builder = new(64 * 1024);

        /// <summary>Starts a file with the header every generated file carries.</summary>
        public SourceText(string description, string version)
        {
            Line("//------------------------------------------------------------------------------");
            Line("// <auto-generated>");
            Line($"//     Generated by DotNet/CldrGenerator from CLDR {version}: {description}.");
            Line("//     Edits here are lost. Regenerate with: dotnet run --project DotNet/CldrGenerator");
            Line("// </auto-generated>");
            Line("//------------------------------------------------------------------------------");
            Line();
        }

        public void Line(string text = "")
        {
            _builder.Append(text).Append('\n');
        }

        /// <summary>Writes <paramref name="items"/> separated by commas, wrapped so no line passes 120 characters.</summary>
        public void WrappedList(string indent, IReadOnlyList<string> items)
        {
            StringBuilder line = new();
            for (int i = 0; i < items.Count; i++)
            {
                string item = i < items.Count - 1 ? items[i] + "," : items[i];
                if (line.Length > 0 && indent.Length + line.Length + 1 + item.Length > 120)
                {
                    Line(indent + line);
                    line.Clear();
                }
                if (line.Length > 0)
                {
                    line.Append(' ');
                }
                line.Append(item);
            }
            if (line.Length > 0)
            {
                Line(indent + line);
            }
        }

        public override string ToString() => _builder.ToString();

        /// <summary>Returns <paramref name="value"/> as a C# string literal in ASCII, with escapes for everything else.</summary>
        public static string Literal(string value)
        {
            StringBuilder literal = new(value.Length + 2);
            literal.Append('"');
            foreach (char character in value)
            {
                if (character == '"' || character == Backslash)
                {
                    literal.Append(Backslash).Append(character);
                }
                else if (character >= 0x20 && character < 0x7F)
                {
                    literal.Append(character);
                }
                else
                {
                    literal.Append(Backslash).Append('u').Append(((int)character).ToString("X4", CultureInfo.InvariantCulture));
                }
            }
            literal.Append('"');
            return literal.ToString();
        }
    }
}
