using System;
using System.Collections.Generic;
using System.Text;

namespace reromanlee.ReactiveLocalizer.Authoring
{
    /// <summary>
    /// Writes the generated code of a catalog: a class of keys with one nested class per table, and a class of
    /// languages. Entries with arguments become methods that take them and return an <c>EntryMessage</c>. The output
    /// depends only on names and argument lists, sorted, so it is identical on every machine and changes only when a
    /// key, alias, argument, table or language does.
    /// </summary>
    /// <remarks>
    /// Every type is written fully qualified, so a project type of the same name never shadows it. A name that
    /// can't be generated is left out and described in the problems instead of producing code that doesn't compile:
    /// an entry named like its own table, which C# forbids, or a name the generated code reserves.
    /// </remarks>
    public static class KeysScriptWriter
    {
        /// <summary>Name of the member that holds each table's key; no entry may take it.</summary>
        public const string TableKeyMember = "TableKey";

        /// <summary>Name of the member that holds the catalog's key; no table may take it.</summary>
        public const string CatalogKeyMember = "CatalogKey";

        private const string Indent = "    ";
        private const string CatalogKeyType = "global::reromanlee.ReactiveLocalizer.CatalogKey";
        private const string TableKeyType = "global::reromanlee.ReactiveLocalizer.TableKey";
        private const string EntryKeyType = "global::reromanlee.ReactiveLocalizer.EntryKey";
        private const string LanguageKeyType = "global::reromanlee.ReactiveLocalizer.LanguageKey";
        private const string EntryMessageType = "global::reromanlee.ReactiveLocalizer.EntryMessage";
        private const string MessageArgumentType = "global::reromanlee.ReactiveLocalizer.MessageArgument";
        private const string MessageNumberType = "global::reromanlee.ReactiveLocalizer.MessageNumber";
        private const string MessageValueType = "global::reromanlee.ReactiveLocalizer.MessageValue";

        // EntryMessage keeps this many arguments without allocating; messages with more pass an array.
        private const int InlineArgumentCapacity = 4;

        private static readonly StringComparer NameOrder = StringComparer.OrdinalIgnoreCase;

        /// <summary>
        /// Returns the source text of <paramref name="script"/>, adding a sentence to <paramref name="problems"/> for
        /// every name it had to leave out.
        /// </summary>
        public static string Write(KeysScript script, ICollection<string> problems)
        {
            StringBuilder builder = new(4096);
            bool hasNamespace = script.NamespaceName.Length > 0;
            if (hasNamespace && !CSharpNames.IsValidNamespace(script.NamespaceName))
            {
                Report(problems, $"'{script.NamespaceName}' is not a valid namespace, so the generated code is in the global namespace.");
                hasNamespace = false;
            }
            string outer = hasNamespace ? Indent : string.Empty;

            AppendLine(builder, "//------------------------------------------------------------------------------");
            AppendLine(builder, "// <auto-generated>");
            AppendLine(builder, $"//     Generated by ReactiveLocalizer from the catalog '{script.CatalogName}'. It changes");
            AppendLine(builder, "//     when a key, alias, argument, table or language changes, never when only a text does.");
            AppendLine(builder, "//     Edits here are lost: edit the catalog and its .lang files instead.");
            AppendLine(builder, "// </auto-generated>");
            AppendLine(builder, "//------------------------------------------------------------------------------");
            AppendLine(builder, string.Empty);
            AppendLine(builder, "#pragma warning disable 1591");
            AppendLine(builder, string.Empty);
            if (hasNamespace)
            {
                AppendLine(builder, $"namespace {script.NamespaceName}");
                AppendLine(builder, "{");
            }
            AppendKeysClass(builder, script, outer, problems);
            AppendLine(builder, string.Empty);
            AppendLanguagesClass(builder, script, outer, problems);
            if (hasNamespace)
            {
                AppendLine(builder, "}");
            }
            return builder.ToString();
        }

        private static void AppendKeysClass(StringBuilder builder, KeysScript script, string outer, ICollection<string> problems)
        {
            string member = outer + Indent;
            AppendLine(builder, $"{outer}/// <summary>");
            AppendLine(builder, $"{outer}/// The tables and entries of the catalog '{script.CatalogName}', as keys the compiler checks.");
            AppendLine(builder, $"{outer}/// </summary>");
            AppendLine(builder, $"{outer}public static class {script.KeysClassName}");
            AppendLine(builder, $"{outer}{{");
            AppendLine(builder, $"{member}/// <summary>The catalog itself, for <c>new Localizer({script.KeysClassName}.{CatalogKeyMember}, host)</c>.</summary>");
            AppendLine(builder, $"{member}public static readonly {CatalogKeyType} {CatalogKeyMember} = new(\"{script.CatalogName}\");");

            List<KeysScriptTable> tables = new(script.Tables);
            tables.Sort((left, right) => CompareNames(left.Name, right.Name));
            for (int i = 0; i < tables.Count; i++)
            {
                KeysScriptTable table = tables[i];
                if (IsSameName(table.Name, CatalogKeyMember) || IsSameName(table.Name, script.KeysClassName))
                {
                    Report(problems, $"The table '{table.Name}' gets no generated keys: '{table.Name}' is a name the generated code reserves.");
                    continue;
                }
                AppendLine(builder, string.Empty);
                AppendTableClass(builder, table, member, problems);
            }
            AppendLine(builder, $"{outer}}}");
        }

        private static void AppendTableClass(StringBuilder builder, KeysScriptTable table, string outer, ICollection<string> problems)
        {
            string member = outer + Indent;
            string tableIdentifier = CSharpNames.ToIdentifier(table.Name);
            AppendLine(builder, $"{outer}/// <summary>The entries of the table '{table.Name}'.</summary>");
            AppendLine(builder, $"{outer}public static class {tableIdentifier}");
            AppendLine(builder, $"{outer}{{");
            AppendLine(builder, $"{member}/// <summary>The table itself.</summary>");
            AppendLine(builder, $"{member}public static readonly {TableKeyType} {TableKeyMember} = new(\"{table.Name}\");");

            // Entries first: an alias forwards to an entry, and static fields initialize in the order they are written.
            List<KeysScriptEntry> entries = new(table.Entries);
            entries.Sort((left, right) => CompareNames(left.Name, right.Name));
            Dictionary<string, KeysScriptEntry> written = new(NameOrder);
            List<KeysScriptEntry> messages = new();
            bool hasEntries = false;
            for (int i = 0; i < entries.Count; i++)
            {
                KeysScriptEntry entry = entries[i];
                if (!IsUsableMember(entry.Name, table.Name, problems, $"The entry '{table.Name}.{entry.Name}'") || written.ContainsKey(entry.Name))
                {
                    continue;
                }
                written.Add(entry.Name, entry);
                if (entry.HasArguments)
                {
                    messages.Add(entry);
                    continue;
                }
                if (!hasEntries)
                {
                    AppendLine(builder, string.Empty);
                    hasEntries = true;
                }
                AppendLine(builder, $"{member}public static readonly {EntryKeyType} {CSharpNames.ToIdentifier(entry.Name)} = new({TableKeyMember}, \"{entry.Name}\");");
            }
            for (int i = 0; i < messages.Count; i++)
            {
                AppendLine(builder, string.Empty);
                AppendMessageMethod(builder, member, messages[i], messages[i].Name, null, MessageKeyField(messages[i].Name));
            }

            List<KeyValuePair<string, string>> aliases = new(table.Aliases);
            aliases.Sort((left, right) => CompareNames(left.Key, right.Key));
            HashSet<string> aliasNames = new(NameOrder);
            for (int i = 0; i < aliases.Count; i++)
            {
                string alias = aliases[i].Key;
                string target = aliases[i].Value;
                if (!IsUsableMember(alias, table.Name, problems, $"The alias '{table.Name}.{alias}'"))
                {
                    continue;
                }
                if (!written.TryGetValue(target, out KeysScriptEntry targetEntry) || written.ContainsKey(alias) || !aliasNames.Add(alias))
                {
                    Report(problems, $"The alias '{table.Name}.{alias}' gets no generated key: it must point to an entry of the table and differ from every entry and alias.");
                    continue;
                }
                AppendLine(builder, string.Empty);
                AppendLine(builder, $"{member}[global::System.Obsolete(\"Renamed to {target}.\")]");
                if (targetEntry.HasArguments)
                {
                    AppendMessageMethod(builder, member, targetEntry, alias, CSharpNames.ToIdentifier(targetEntry.Name), null);
                }
                else
                {
                    AppendLine(builder, $"{member}public static readonly {EntryKeyType} {CSharpNames.ToIdentifier(alias)} = {CSharpNames.ToIdentifier(target)};");
                }
            }

            // A moved entry keeps its former name here, building its key directly, so it compiles whether or not the
            // table it moved to generates code.
            List<KeysScriptMovedEntry> moved = new(table.MovedEntries);
            moved.Sort((left, right) => CompareNames(left.FormerName, right.FormerName));
            List<KeysScriptMovedEntry> movedMessages = new();
            for (int i = 0; i < moved.Count; i++)
            {
                KeysScriptMovedEntry entry = moved[i];
                if (!IsUsableMember(entry.FormerName, table.Name, problems, $"The moved entry '{table.Name}.{entry.FormerName}'"))
                {
                    continue;
                }
                if (written.ContainsKey(entry.FormerName) || !aliasNames.Add(entry.FormerName))
                {
                    Report(problems, $"The moved entry '{table.Name}.{entry.FormerName}' gets no generated key: an entry or alias of the table has its name.");
                    continue;
                }
                string movedTo = $"{entry.TableName}.{entry.Entry.Name}";
                AppendLine(builder, string.Empty);
                AppendLine(builder, $"{member}[global::System.Obsolete(\"Moved to {movedTo}.\")]");
                if (entry.Entry.HasArguments)
                {
                    AppendMessageMethod(builder, member, entry.Entry, entry.FormerName, null, MessageKeyField(entry.FormerName));
                    movedMessages.Add(entry);
                }
                else
                {
                    AppendLine(builder, $"{member}public static readonly {EntryKeyType} {CSharpNames.ToIdentifier(entry.FormerName)} = new(\"{entry.TableName}\", \"{entry.Entry.Name}\");");
                }
            }

            // The keys of message entries are private: their methods hand them out with the arguments.
            if (messages.Count > 0 || movedMessages.Count > 0)
            {
                AppendLine(builder, string.Empty);
            }
            for (int i = 0; i < messages.Count; i++)
            {
                AppendLine(builder, $"{member}private static readonly {EntryKeyType} {MessageKeyField(messages[i].Name)} = new({TableKeyMember}, \"{messages[i].Name}\");");
            }
            for (int i = 0; i < movedMessages.Count; i++)
            {
                KeysScriptMovedEntry entry = movedMessages[i];
                AppendLine(builder, $"{member}private static readonly {EntryKeyType} {MessageKeyField(entry.FormerName)} = new(\"{entry.TableName}\", \"{entry.Entry.Name}\");");
            }
            AppendLine(builder, $"{outer}}}");
        }

        /// <summary>
        /// Writes the method of a message entry, named <paramref name="methodName"/>. An alias passes its arguments on to
        /// the method <paramref name="forwardTo"/>; anything else creates its message with the key in <paramref name="keyField"/>.
        /// </summary>
        private static void AppendMessageMethod(StringBuilder builder, string member, KeysScriptEntry entry, string methodName, string forwardTo, string keyField)
        {
            StringBuilder parameters = new();
            StringBuilder names = new();
            for (int i = 0; i < entry.Arguments.Count; i++)
            {
                KeysScriptArgument argument = entry.Arguments[i];
                if (i > 0)
                {
                    parameters.Append(", ");
                    names.Append(", ");
                }
                parameters.Append(ParameterType(argument.Kind)).Append(' ').Append(CSharpNames.ToIdentifier(argument.Name));
                names.Append(CSharpNames.ToIdentifier(argument.Name));
            }
            AppendLine(builder, $"{member}public static {EntryMessageType} {CSharpNames.ToIdentifier(methodName)}({parameters}) =>");
            if (forwardTo != null)
            {
                AppendLine(builder, $"{member}{Indent}{forwardTo}({names});");
                return;
            }
            StringBuilder arguments = new();
            for (int i = 0; i < entry.Arguments.Count; i++)
            {
                KeysScriptArgument argument = entry.Arguments[i];
                if (i > 0)
                {
                    arguments.Append(", ");
                }
                arguments.Append($"new {MessageArgumentType}(\"{argument.Name}\", {CSharpNames.ToIdentifier(argument.Name)})");
            }
            AppendLine(builder, entry.Arguments.Count <= InlineArgumentCapacity
                ? $"{member}{Indent}new({keyField}, {arguments});"
                : $"{member}{Indent}new({keyField}, new {MessageArgumentType}[] {{ {arguments} }});");
        }

        /// <summary>The private field of a message entry's key; entry names never start with an underscore, so it can't clash.</summary>
        private static string MessageKeyField(string entryName) => "_" + entryName;

        private static string ParameterType(MessageArgumentKind kind) => kind switch
        {
            MessageArgumentKind.Number => MessageNumberType,
            MessageArgumentKind.Keyword => "string",
            _ => MessageValueType
        };

        private static void AppendLanguagesClass(StringBuilder builder, KeysScript script, string outer, ICollection<string> problems)
        {
            string member = outer + Indent;
            AppendLine(builder, $"{outer}/// <summary>");
            AppendLine(builder, $"{outer}/// The languages of the catalog '{script.CatalogName}'.");
            AppendLine(builder, $"{outer}/// </summary>");
            AppendLine(builder, $"{outer}public static class {script.LanguagesClassName}");
            AppendLine(builder, $"{outer}{{");
            List<string> languages = new(script.Languages);
            languages.Sort(CompareNames);
            for (int i = 0; i < languages.Count; i++)
            {
                string language = languages[i];
                if (IsSameName(language, script.LanguagesClassName))
                {
                    Report(problems, $"The language '{language}' gets no generated key: a member can't share the name of its class.");
                    continue;
                }
                AppendLine(builder, $"{member}public static readonly {LanguageKeyType} {CSharpNames.ToIdentifier(language)} = new(\"{language}\");");
            }
            AppendLine(builder, $"{outer}}}");
        }

        /// <summary>
        /// Returns whether a name can be a member of its table's class: C# forbids a member named like its class, and
        /// the table's own key takes <see cref="TableKeyMember"/>.
        /// </summary>
        private static bool IsUsableMember(string name, string tableName, ICollection<string> problems, string subject)
        {
            if (IsSameName(name, tableName))
            {
                Report(problems, $"{subject} gets no generated key: C# doesn't allow a member named like its class. Rename the entry or the table.");
                return false;
            }
            if (IsSameName(name, TableKeyMember))
            {
                Report(problems, $"{subject} gets no generated key: '{TableKeyMember}' holds the table's own key.");
                return false;
            }
            return true;
        }

        private static int CompareNames(string left, string right)
        {
            int comparison = NameOrder.Compare(left, right);
            return comparison != 0 ? comparison : string.CompareOrdinal(left, right);
        }

        private static bool IsSameName(string left, string right) => string.Equals(left, right, StringComparison.OrdinalIgnoreCase);

        private static void AppendLine(StringBuilder builder, string line)
        {
            // Always \n, so the output is byte-identical on every platform.
            builder.Append(line).Append('\n');
        }

        private static void Report(ICollection<string> problems, string problem)
        {
            problems?.Add(problem);
        }
    }
}
