//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by DotNet/CldrGenerator from CLDR 48.2.3: cldr-numbers-full and numberingSystems.json.
//     Edits here are lost. Regenerate with: dotnet run --project DotNet/CldrGenerator
// </auto-generated>
//------------------------------------------------------------------------------

namespace reromanlee.ReactiveLocalizer.Formatting
{
    /// <summary>
    /// CLDR's number symbols: the distinct sets locales use, and the locales that can't find theirs by shortening
    /// their tag. Every other CLDR locale has the same symbols as the locale its tag shortens to, such as
    /// <c>en-GB</c> and <c>en</c>, so a lookup that shortens the tag until it finds one gets exactly CLDR's data.
    /// </summary>
    internal static class CldrNumberSymbols
    {
        /// <summary>The CLDR release the symbols come from.</summary>
        public const string Version = "48.2.3";

        /// <summary>How many distinct symbol sets there are.</summary>
        public const int SetCount = 52;

        /// <summary>The set of the root locale, for languages without a culture or a fallback.</summary>
        public const int RootSet = 0;

        /// <summary>The locales a lookup has to find directly, sorted ordinally for binary search.</summary>
        private static readonly string[] Locales =
        {
            "aa", "ab", "af", "agq", "ak", "am", "an", "ann", "apc", "ar", "ar-BH", "ar-DJ", "ar-DZ", "ar-EG", "ar-ER",
            "ar-IL", "ar-IQ", "ar-JO", "ar-KM", "ar-KW", "ar-LB", "ar-LY", "ar-MA", "ar-MR", "ar-OM", "ar-PS", "ar-QA",
            "ar-SA", "ar-SD", "ar-SO", "ar-SS", "ar-SY", "ar-TD", "ar-TN", "ar-YE", "arn", "as", "asa", "ast", "az",
            "az-Arab", "ba", "bal", "bas", "be", "bem", "bew", "bez", "bg", "bgc", "bgn", "bho", "blo", "blt", "bm",
            "bn", "bo", "bqi", "br", "brx", "bs", "bss", "bua", "byn", "ca", "cad", "cch", "ccp", "ce", "ceb", "cgg",
            "cho", "chr", "cic", "ckb", "co", "cop", "cs", "csw", "cu", "cv", "cy", "da", "dav", "de", "de-AT", "de-CH",
            "de-LI", "dje", "doi", "dsb", "dua", "dv", "dyo", "dz", "ebu", "ee", "el", "en", "en-AT", "en-BE", "en-CH",
            "en-CZ", "en-DE", "en-DK", "en-EE", "en-ES", "en-FI", "en-FR", "en-GE", "en-HU", "en-ID", "en-IN", "en-IT",
            "en-LT", "en-LV", "en-NL", "en-NO", "en-PL", "en-PT", "en-RO", "en-SE", "en-SI", "en-SK", "en-UA", "en-ZA",
            "eo", "es", "es-419", "es-AR", "es-BO", "es-BR", "es-BZ", "es-CL", "es-CO", "es-CR", "es-CU", "es-DO",
            "es-EC", "es-GT", "es-HN", "es-MX", "es-NI", "es-PA", "es-PE", "es-PR", "es-PY", "es-SV", "es-US", "es-UY",
            "es-VE", "et", "eu", "ewo", "fa", "ff", "ff-Adlm", "fi", "fil", "fo", "fr", "fr-CA", "fr-CH", "fr-LU",
            "fr-MA", "frr", "fur", "fy", "ga", "gaa", "gd", "gez", "gl", "gn", "gsw", "gu", "guz", "gv", "ha", "haw",
            "he", "hi", "hnj", "hr", "hsb", "ht", "hu", "hy", "ia", "id", "ie", "ig", "ii", "io", "is", "it", "it-CH",
            "iu", "ja", "jbo", "jgo", "jmc", "jv", "ka", "kaa", "kab", "kaj", "kam", "kcg", "kde", "kea", "kek", "ken",
            "kgp", "khq", "ki", "kk", "kk-Arab", "kkj", "kl", "kln", "km", "kn", "ko", "kok", "kpe", "ks", "ks-Deva",
            "ksb", "ksf", "ksh", "ku", "ku-Arab", "kw", "kxv", "ky", "la", "lag", "lb", "lg", "lij", "lkt", "lld",
            "lmo", "ln", "lo", "lrc", "lt", "ltg", "lu", "luo", "luy", "lv", "lzz", "mai", "mas", "mdf", "mer", "mfe",
            "mg", "mgh", "mgo", "mhn", "mi", "mic", "mk", "ml", "mn", "mni", "mni-Mtei", "moh", "mr", "ms",
            "ms-Arab-BN", "ms-BN", "ms-ID", "mt", "mua", "mus", "mww", "my", "myv", "mzn", "naq", "nb", "nd", "nds",
            "ne", "nl", "nmg", "nn", "nnh", "no", "nqo", "nr", "nso", "nus", "nv", "ny", "nyn", "oc", "oka", "om", "or",
            "os", "osa", "pa", "pa-Arab", "pap", "pcm", "pi", "pis", "pl", "pms", "prg", "ps", "pt", "pt-AO", "pt-CH",
            "pt-CV", "pt-GQ", "pt-GW", "pt-LU", "pt-MO", "pt-MZ", "pt-PT", "pt-ST", "pt-TL", "qu", "qu-BO", "quc",
            "raj", "rhg", "rif", "rm", "rn", "ro", "rof", "ru", "ru-UA", "rw", "rwk", "sa", "sah", "saq", "sat",
            "sat-Deva", "sbp", "sc", "scn", "sd", "sd-Deva", "sdh", "se", "seh", "ses", "sg", "sgs", "shi", "shn", "si",
            "sid", "sk", "skr", "sl", "sma", "smj", "smn", "sms", "sn", "so", "sq", "sr", "ss", "ssy", "st", "su",
            "suz", "sv", "sw", "sw-CD", "syr", "szl", "ta", "ta-MY", "ta-SG", "te", "teo", "tg", "th", "ti", "tig",
            "tk", "tn", "to", "tok", "tpi", "tr", "trv", "trw", "ts", "tt", "twq", "tyv", "tzm", "ug", "uk", "und",
            "ur", "ur-IN", "uz", "uz-Arab", "vai", "ve", "vec", "vi", "vmw", "vo", "vun", "wa", "wae", "wal", "wbp",
            "wo", "xh", "xnr", "xog", "yav", "yi", "yo", "yrl", "yue", "za", "zgh", "zh", "zu"
        };

        /// <summary>The symbol set of each locale in <see cref="Locales"/>.</summary>
        private static readonly byte[] Sets =
        {
            0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 0,
            5, 0, 6, 6, 7, 8, 0, 9, 10, 0, 0, 0, 11, 12, 7, 12, 13, 0, 0, 14, 0, 0, 9, 15, 6, 0, 9, 0, 16, 0, 0, 17, 18,
            0, 0, 0, 0, 0, 19, 0, 0, 9, 0, 0, 9, 0, 16, 0, 16, 9, 20, 20, 8, 0, 16, 9, 0, 1, 21, 0, 22, 6, 0, 16, 6, 20,
            1, 16, 16, 1, 6, 9, 23, 23, 1, 6, 15, 6, 1, 1, 6, 9, 6, 1, 6, 9, 6, 1, 1, 1, 23, 24, 0, 6, 6, 0, 0, 6, 6, 1,
            0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 6, 6, 25, 26, 1, 27, 1, 28, 29, 0, 30, 31, 9, 32, 16, 16, 0, 6, 6, 0,
            0, 0, 0, 16, 0, 33, 15, 0, 0, 0, 0, 34, 15, 35, 30, 16, 9, 11, 11, 36, 6, 11, 0, 0, 0, 6, 36, 37, 0, 0, 0,
            6, 0, 6, 11, 0, 1, 0, 0, 0, 0, 1, 0, 0, 6, 8, 0, 1, 0, 6, 16, 0, 0, 0, 0, 38, 0, 7, 0, 0, 1, 29, 39, 0, 0,
            38, 1, 0, 0, 16, 0, 6, 0, 6, 32, 6, 6, 7, 29, 0, 6, 0, 0, 11, 0, 0, 0, 0, 0, 8, 0, 6, 0, 0, 0, 0, 16, 38, 0,
            40, 41, 0, 42, 0, 6, 6, 6, 0, 6, 0, 35, 43, 0, 7, 0, 29, 0, 16, 44, 6, 1, 29, 6, 29, 45, 1, 0, 0, 0, 0, 0,
            46, 0, 0, 38, 1, 0, 15, 7, 0, 0, 0, 0, 11, 6, 1, 7, 6, 1, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 18, 16, 0,
            12, 0, 0, 23, 16, 16, 0, 9, 10, 6, 0, 44, 1, 0, 47, 12, 0, 6, 6, 48, 0, 3, 29, 6, 8, 6, 0, 1, 0, 0, 0, 9, 0,
            49, 0, 0, 9, 0, 0, 0, 11, 6, 1, 0, 0, 6, 0, 29, 0, 6, 0, 1, 15, 0, 0, 38, 0, 1, 0, 0, 0, 9, 20, 0, 50, 0,
            39, 0, 0, 1, 9, 8, 8, 1, 0, 1, 0, 34, 51, 1, 7, 0, 1, 23, 6, 6, 0, 0, 0, 32, 0, 0, 6, 8, 15, 0, 1, 0, 0, 6,
            0, 0, 9, 0, 0
        };

        /// <summary>Returns the symbol set of a CLDR locale written exactly as CLDR names it, or -1.</summary>
        public static int Find(string locale)
        {
            int index = global::System.Array.BinarySearch(Locales, locale, global::System.StringComparer.Ordinal);
            return index >= 0 ? Sets[index] : -1;
        }

        /// <summary>Creates the symbols of the set <paramref name="set"/>.</summary>
        public static NumberSymbols Create(int set)
        {
            switch (set)
            {
                case 0:
                    return new NumberSymbols(".", ",", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 1:
                    return new NumberSymbols(",", "\u00A0", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 2:
                    return new NumberSymbols(".", ",", "0123456789", 1,
                        new NumberPattern("", "", "\u200E-", "", 3, 3, 3),
                        new NumberPattern("", "\u200E%\u200E", "\u200E-", "\u200E%\u200E", 3, 3, 0));
                case 3:
                    return new NumberSymbols("\u066B", "\u066C", "\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669", 1,
                        new NumberPattern("", "", "\u061C-", "", 3, 3, 3),
                        new NumberPattern("", "\u066A\u061C", "\u061C-", "\u066A\u061C", 3, 3, 0));
                case 4:
                    return new NumberSymbols(",", ".", "0123456789", 1,
                        new NumberPattern("", "", "\u200E-", "", 3, 3, 3),
                        new NumberPattern("", "\u200E%\u200E", "\u200E-", "\u200E%\u200E", 3, 3, 0));
                case 5:
                    return new NumberSymbols(".", ",", "\u09E6\u09E7\u09E8\u09E9\u09EA\u09EB\u09EC\u09ED\u09EE\u09EF", 1,
                        new NumberPattern("", "", "-", "", 3, 2, 3),
                        new NumberPattern("", "%", "-", "%", 3, 2, 0));
                case 6:
                    return new NumberSymbols(",", ".", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 7:
                    return new NumberSymbols("\u066B", "\u066C", "\u06F0\u06F1\u06F2\u06F3\u06F4\u06F5\u06F6\u06F7\u06F8\u06F9", 1,
                        new NumberPattern("", "", "\u200E-\u200E", "", 3, 3, 3),
                        new NumberPattern("", "\u066A", "\u200E-\u200E", "\u066A", 3, 3, 0));
                case 8:
                    return new NumberSymbols(".", "\u00A0", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 9:
                    return new NumberSymbols(",", "\u00A0", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "\u00A0%", "-", "\u00A0%", 3, 3, 0));
                case 10:
                    return new NumberSymbols(",", "\u00A0", "0123456789", 2,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "\u00A0%", "-", "\u00A0%", 3, 3, 0));
                case 11:
                    return new NumberSymbols(",", "\u00A0", "0123456789", 2,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 12:
                    return new NumberSymbols(".", ",", "\u0966\u0967\u0968\u0969\u096A\u096B\u096C\u096D\u096E\u096F", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 13:
                    return new NumberSymbols(",", "\u00A0", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("%\u00A0", "", "%\u00A0-", "", 2, 2, 0));
                case 14:
                    return new NumberSymbols(".", ",", "\u09E6\u09E7\u09E8\u09E9\u09EA\u09EB\u09EC\u09ED\u09EE\u09EF", 1,
                        new NumberPattern("", "", "-", "", 3, 2, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 15:
                    return new NumberSymbols(".", ",", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 2, 3),
                        new NumberPattern("", "%", "-", "%", 3, 2, 0));
                case 16:
                    return new NumberSymbols(",", ".", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "\u00A0%", "-", "\u00A0%", 3, 3, 0));
                case 17:
                    return new NumberSymbols(".", ",", "\uD804\uDD36\uD804\uDD37\uD804\uDD38\uD804\uDD39\uD804\uDD3A\uD804\uDD3B\uD804\uDD3C\uD804\uDD3D\uD804\uDD3E\uD804\uDD3F", 1,
                        new NumberPattern("", "", "-", "", 3, 2, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 18:
                    return new NumberSymbols(".", ",", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "\u00A0%", "-", "\u00A0%", 3, 3, 0));
                case 19:
                    return new NumberSymbols("\u066B", "\u066C", "\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669", 1,
                        new NumberPattern("", "", "\u200F-", "", 3, 3, 3),
                        new NumberPattern("", "\u00A0\u066A", "\u200F-", "\u00A0\u066A", 3, 3, 0));
                case 20:
                    return new NumberSymbols(".", "'", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 21:
                    return new NumberSymbols(".", ",", "\u0F20\u0F21\u0F22\u0F23\u0F24\u0F25\u0F26\u0F27\u0F28\u0F29", 1,
                        new NumberPattern("", "", "-", "", 3, 2, 3),
                        new NumberPattern("", "\u00A0%", "-", "\u00A0%", 3, 2, 0));
                case 22:
                    return new NumberSymbols(".", ",", "0123456789", 3,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 23:
                    return new NumberSymbols(",", "\u202F", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 24:
                    return new NumberSymbols(",", ".", "0123456789", 2,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "\u00A0%", "-", "\u00A0%", 3, 3, 0));
                case 25:
                    return new NumberSymbols(",", "\u00A0", "0123456789", 2,
                        new NumberPattern("", "", "\u2212", "", 3, 3, 3),
                        new NumberPattern("", "%", "\u2212", "%", 3, 3, 0));
                case 26:
                    return new NumberSymbols(",", ".", "0123456789", 1,
                        new NumberPattern("", "", "\u2212", "", 3, 3, 3),
                        new NumberPattern("%\u00A0", "", "\u2212%\u00A0", "", 3, 3, 0));
                case 27:
                    return new NumberSymbols("\u066B", "\u066C", "\u06F0\u06F1\u06F2\u06F3\u06F4\u06F5\u06F6\u06F7\u06F8\u06F9", 1,
                        new NumberPattern("", "", "\u200E\u2212", "", 3, 3, 3),
                        new NumberPattern("", "\u066A", "\u200E\u2212", "\u066A", 3, 3, 0));
                case 28:
                    return new NumberSymbols(".", "\u2E41", "\uD83A\uDD50\uD83A\uDD51\uD83A\uDD52\uD83A\uDD53\uD83A\uDD54\uD83A\uDD55\uD83A\uDD56\uD83A\uDD57\uD83A\uDD58\uD83A\uDD59", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 29:
                    return new NumberSymbols(",", "\u00A0", "0123456789", 1,
                        new NumberPattern("", "", "\u2212", "", 3, 3, 3),
                        new NumberPattern("", "\u00A0%", "\u2212", "\u00A0%", 3, 3, 0));
                case 30:
                    return new NumberSymbols(",", ".", "0123456789", 1,
                        new NumberPattern("", "", "\u2212", "", 3, 3, 3),
                        new NumberPattern("", "\u00A0%", "\u2212", "\u00A0%", 3, 3, 0));
                case 31:
                    return new NumberSymbols(",", "\u202F", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "\u00A0%", "-", "\u00A0%", 3, 3, 0));
                case 32:
                    return new NumberSymbols(",", "'", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 33:
                    return new NumberSymbols(".", "'", "0123456789", 1,
                        new NumberPattern("", "", "\u2212", "", 3, 3, 3),
                        new NumberPattern("", "\u00A0%", "\u2212", "\u00A0%", 3, 3, 0));
                case 34:
                    return new NumberSymbols(".", ",", "0123456789", 1,
                        new NumberPattern("", "", "\u200E-", "", 3, 3, 3),
                        new NumberPattern("", "%", "\u200E-", "%", 3, 3, 0));
                case 35:
                    return new NumberSymbols(".", ",", "\uD838\uDD40\uD838\uDD41\uD838\uDD42\uD838\uDD43\uD838\uDD44\uD838\uDD45\uD838\uDD46\uD838\uDD47\uD838\uDD48\uD838\uDD49", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 36:
                    return new NumberSymbols(",", ".", "0123456789", 2,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 37:
                    return new NumberSymbols(".", "'", "0123456789", 2,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 38:
                    return new NumberSymbols(".", ",", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 2, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 39:
                    return new NumberSymbols(",", ".", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("%", "", "-%", "", 3, 3, 0));
                case 40:
                    return new NumberSymbols(".", ",", "\u09E6\u09E7\u09E8\u09E9\u09EA\u09EB\u09EC\u09ED\u09EE\u09EF", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 41:
                    return new NumberSymbols(".", ",", "\uABF0\uABF1\uABF2\uABF3\uABF4\uABF5\uABF6\uABF7\uABF8\uABF9", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 42:
                    return new NumberSymbols(".", ",", "\u0966\u0967\u0968\u0969\u096A\u096B\u096C\u096D\u096E\u096F", 1,
                        new NumberPattern("", "", "-", "", 3, 2, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 43:
                    return new NumberSymbols(".", ",", "\u1040\u1041\u1042\u1043\u1044\u1045\u1046\u1047\u1048\u1049", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 44:
                    return new NumberSymbols(".", ",", "\u0966\u0967\u0968\u0969\u096A\u096B\u096C\u096D\u096E\u096F", 1,
                        new NumberPattern("", "", "-", "", 3, 2, 3),
                        new NumberPattern("", "%", "-", "%", 3, 2, 0));
                case 45:
                    return new NumberSymbols(".", "\u060C", "\u07C0\u07C1\u07C2\u07C3\u07C4\u07C5\u07C6\u07C7\u07C8\u07C9", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 46:
                    return new NumberSymbols(",", "\u00A0", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "\u202F%", "-", "\u202F%", 3, 3, 0));
                case 47:
                    return new NumberSymbols(".", ",", "\u1C50\u1C51\u1C52\u1C53\u1C54\u1C55\u1C56\u1C57\u1C58\u1C59", 1,
                        new NumberPattern("", "", "-", "", 3, 3, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 48:
                    return new NumberSymbols(".", "\u066C", "\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669", 1,
                        new NumberPattern("", "", "\u061C-", "", 3, 3, 3),
                        new NumberPattern("", "\u066A\u061C", "\u061C-", "\u066A\u061C", 3, 3, 0));
                case 49:
                    return new NumberSymbols(",", ".", "0123456789", 2,
                        new NumberPattern("", "", "\u2212", "", 3, 3, 3),
                        new NumberPattern("", "\u00A0%", "\u2212", "\u00A0%", 3, 3, 0));
                case 50:
                    return new NumberSymbols(",", "\u00A0", "0123456789", 1,
                        new NumberPattern("", "", "-", "", 2, 2, 3),
                        new NumberPattern("", "%", "-", "%", 3, 3, 0));
                case 51:
                    return new NumberSymbols("\u066B", "\u066C", "\u06F0\u06F1\u06F2\u06F3\u06F4\u06F5\u06F6\u06F7\u06F8\u06F9", 1,
                        new NumberPattern("", "", "\u200E-\u200E", "", 3, 3, 3),
                        new NumberPattern("", "%", "\u200E-\u200E", "%", 3, 3, 0));
            }
            throw new global::System.ArgumentOutOfRangeException(nameof(set));
        }
    }
}
