//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by DotNet/CldrGenerator from CLDR 48.2.3: plurals.json and ordinals.json.
//     Edits here are lost. Regenerate with: dotnet run --project DotNet/CldrGenerator
// </auto-generated>
//------------------------------------------------------------------------------

namespace reromanlee.ReactiveLocalizer.Formatting
{
    /// <summary>
    /// CLDR's plural rules as code: which rule set each locale uses, the forms each set has, and the conditions
    /// that choose a form for a number. Rule set 0 is the root locale's, which chooses <c>other</c> for every number.
    /// </summary>
    internal static class CldrPluralRules
    {
        /// <summary>The CLDR release the rules come from.</summary>
        public const string Version = "48.2.3";

        /// <summary>Every locale with cardinal rules, sorted ordinally for binary search.</summary>
        private static readonly string[] CardinalLocales =
        {
            "af", "ak", "am", "an", "ar", "ars", "as", "asa", "ast", "az", "bal", "be", "bem", "bez", "bg", "bho",
            "blo", "bm", "bn", "bo", "br", "brx", "bs", "ca", "ce", "ceb", "cgg", "chr", "ckb", "cs", "csw", "cv", "cy",
            "da", "de", "doi", "dsb", "dv", "dz", "ee", "el", "en", "eo", "es", "et", "eu", "fa", "ff", "fi", "fil",
            "fo", "fr", "fur", "fy", "ga", "gd", "gl", "gsw", "gu", "guw", "gv", "ha", "haw", "he", "hi", "hnj", "hr",
            "hsb", "hu", "hy", "ia", "id", "ie", "ig", "ii", "io", "is", "it", "iu", "ja", "jbo", "jgo", "jmc", "jv",
            "jw", "ka", "kab", "kaj", "kcg", "kde", "kea", "kk", "kkj", "kl", "km", "kn", "ko", "kok", "kok-Latn", "ks",
            "ksb", "ksh", "ku", "kw", "ky", "lag", "lb", "lg", "lij", "lkt", "lld", "ln", "lo", "lt", "lv", "mas", "mg",
            "mgo", "mk", "ml", "mn", "mo", "mr", "ms", "mt", "my", "nah", "naq", "nb", "nd", "ne", "nl", "nn", "nnh",
            "no", "nqo", "nr", "nso", "ny", "nyn", "om", "or", "os", "osa", "pa", "pap", "pcm", "pl", "prg", "ps", "pt",
            "pt-PT", "rm", "ro", "rof", "ru", "rwk", "sah", "saq", "sat", "sc", "scn", "sd", "sdh", "se", "seh", "ses",
            "sg", "sgs", "sh", "shi", "si", "sk", "sl", "sma", "smi", "smj", "smn", "sms", "sn", "so", "sq", "sr", "ss",
            "ssy", "st", "su", "sv", "sw", "syr", "ta", "te", "teo", "th", "ti", "tig", "tk", "tl", "tn", "to", "tpi",
            "tr", "ts", "tzm", "ug", "uk", "und", "ur", "uz", "ve", "vec", "vi", "vo", "vun", "wa", "wae", "wo", "xh",
            "xog", "yi", "yo", "yue", "zh", "zu"
        };

        /// <summary>The rule set of each locale in <see cref="CardinalLocales"/>.</summary>
        private static readonly byte[] CardinalSets =
        {
            1, 2, 3, 1, 4, 4, 3, 1, 5, 1, 1, 6, 1, 1, 1, 2, 7, 0, 3, 0, 8, 1, 9, 10, 1, 11, 1, 1, 1, 12, 2, 7, 13, 14,
            5, 3, 15, 1, 0, 1, 1, 5, 1, 16, 5, 1, 3, 17, 5, 11, 1, 18, 1, 5, 19, 20, 5, 1, 3, 2, 21, 1, 1, 22, 3, 0, 9,
            15, 1, 17, 5, 0, 5, 0, 0, 5, 23, 10, 24, 0, 0, 1, 1, 0, 0, 1, 17, 1, 1, 0, 0, 1, 1, 1, 0, 3, 0, 3, 3, 1, 1,
            7, 1, 25, 1, 26, 1, 1, 5, 0, 10, 2, 0, 27, 28, 1, 2, 1, 29, 1, 1, 30, 1, 0, 31, 0, 1, 24, 1, 1, 1, 5, 1, 1,
            1, 0, 1, 2, 1, 1, 1, 1, 1, 0, 2, 1, 3, 32, 28, 1, 33, 10, 1, 30, 1, 34, 1, 0, 1, 24, 5, 10, 1, 1, 24, 1, 0,
            0, 35, 9, 36, 37, 12, 38, 24, 24, 24, 24, 24, 1, 1, 1, 9, 1, 1, 1, 0, 5, 5, 1, 1, 1, 1, 0, 2, 1, 1, 11, 1,
            0, 0, 1, 1, 39, 1, 34, 0, 5, 1, 1, 10, 0, 1, 1, 2, 1, 0, 1, 1, 5, 0, 0, 0, 3
        };

        /// <summary>Every locale with ordinal rules, sorted ordinally for binary search.</summary>
        private static readonly string[] OrdinalLocales =
        {
            "af", "am", "an", "ar", "as", "ast", "az", "bal", "be", "bg", "blo", "bn", "bs", "ca", "ce", "cs", "cv",
            "cy", "da", "de", "dsb", "el", "en", "es", "et", "eu", "fa", "fi", "fil", "fr", "fy", "ga", "gd", "gl",
            "gsw", "gu", "he", "hi", "hr", "hsb", "hu", "hy", "ia", "id", "ie", "is", "it", "ja", "ka", "kk", "km",
            "kn", "ko", "kok", "kok-Latn", "kw", "ky", "lij", "lld", "lo", "lt", "lv", "mk", "ml", "mn", "mo", "mr",
            "ms", "my", "nb", "ne", "nl", "no", "or", "pa", "pl", "prg", "ps", "pt", "ro", "ru", "sc", "scn", "sd",
            "sh", "si", "sk", "sl", "sq", "sr", "sv", "sw", "ta", "te", "th", "tk", "tl", "tpi", "tr", "uk", "und",
            "ur", "uz", "vec", "vi", "yue", "zh", "zu"
        };

        /// <summary>The rule set of each locale in <see cref="OrdinalLocales"/>.</summary>
        private static readonly byte[] OrdinalSets =
        {
            0, 0, 0, 0, 1, 0, 2, 3, 4, 0, 5, 1, 0, 6, 0, 0, 0, 7, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 3, 3, 0, 3, 9, 0, 0, 10,
            0, 10, 0, 0, 11, 3, 0, 0, 0, 0, 12, 0, 13, 14, 0, 0, 0, 15, 15, 16, 0, 17, 12, 3, 0, 0, 18, 0, 0, 3, 15, 3,
            0, 0, 19, 0, 0, 20, 0, 0, 0, 0, 0, 3, 0, 12, 17, 0, 0, 0, 0, 0, 21, 0, 22, 0, 0, 0, 0, 23, 3, 0, 0, 24, 0,
            0, 0, 12, 3, 0, 0, 0
        };

        /// <summary>Returns the cardinal rule set of a CLDR locale, or -1 when CLDR has none for it.</summary>
        public static int FindCardinal(string locale) => Find(CardinalLocales, CardinalSets, locale);

        /// <summary>Returns the ordinal rule set of a CLDR locale, or -1 when CLDR has none for it.</summary>
        public static int FindOrdinal(string locale) => Find(OrdinalLocales, OrdinalSets, locale);

        /// <summary>Returns the forms a cardinal rule set uses, one bit per <see cref="PluralCategory"/>.</summary>
        public static int GetCardinalCategories(int rules)
        {
            switch (rules)
            {
                case 1:
                    return 0b100010; // one, other
                case 2:
                    return 0b100010; // one, other
                case 3:
                    return 0b100010; // one, other
                case 4:
                    return 0b111111; // zero, one, two, few, many, other
                case 5:
                    return 0b100010; // one, other
                case 6:
                    return 0b111010; // one, few, many, other
                case 7:
                    return 0b100011; // zero, one, other
                case 8:
                    return 0b111110; // one, two, few, many, other
                case 9:
                    return 0b101010; // one, few, other
                case 10:
                    return 0b110010; // one, many, other
                case 11:
                    return 0b100010; // one, other
                case 12:
                    return 0b111010; // one, few, many, other
                case 13:
                    return 0b111111; // zero, one, two, few, many, other
                case 14:
                    return 0b100010; // one, other
                case 15:
                    return 0b101110; // one, two, few, other
                case 16:
                    return 0b110010; // one, many, other
                case 17:
                    return 0b100010; // one, other
                case 18:
                    return 0b110010; // one, many, other
                case 19:
                    return 0b111110; // one, two, few, many, other
                case 20:
                    return 0b101110; // one, two, few, other
                case 21:
                    return 0b111110; // one, two, few, many, other
                case 22:
                    return 0b100110; // one, two, other
                case 23:
                    return 0b100010; // one, other
                case 24:
                    return 0b100110; // one, two, other
                case 25:
                    return 0b111111; // zero, one, two, few, many, other
                case 26:
                    return 0b100011; // zero, one, other
                case 27:
                    return 0b111010; // one, few, many, other
                case 28:
                    return 0b100011; // zero, one, other
                case 29:
                    return 0b100010; // one, other
                case 30:
                    return 0b101010; // one, few, other
                case 31:
                    return 0b111110; // one, two, few, many, other
                case 32:
                    return 0b111010; // one, few, many, other
                case 33:
                    return 0b110010; // one, many, other
                case 34:
                    return 0b111010; // one, few, many, other
                case 35:
                    return 0b111110; // one, two, few, many, other
                case 36:
                    return 0b101010; // one, few, other
                case 37:
                    return 0b100010; // one, other
                case 38:
                    return 0b101110; // one, two, few, other
                case 39:
                    return 0b100010; // one, other
            }
            return PluralCategories.OtherOnly;
        }

        /// <summary>Returns the forms an ordinal rule set uses, one bit per <see cref="PluralCategory"/>.</summary>
        public static int GetOrdinalCategories(int rules)
        {
            switch (rules)
            {
                case 1:
                    return 0b111110; // one, two, few, many, other
                case 2:
                    return 0b111010; // one, few, many, other
                case 3:
                    return 0b100010; // one, other
                case 4:
                    return 0b101000; // few, other
                case 5:
                    return 0b101011; // zero, one, few, other
                case 6:
                    return 0b101110; // one, two, few, other
                case 7:
                    return 0b111111; // zero, one, two, few, many, other
                case 8:
                    return 0b101110; // one, two, few, other
                case 9:
                    return 0b101110; // one, two, few, other
                case 10:
                    return 0b111110; // one, two, few, many, other
                case 11:
                    return 0b100010; // one, other
                case 12:
                    return 0b110000; // many, other
                case 13:
                    return 0b110010; // one, many, other
                case 14:
                    return 0b110000; // many, other
                case 15:
                    return 0b101110; // one, two, few, other
                case 16:
                    return 0b110010; // one, many, other
                case 17:
                    return 0b110000; // many, other
                case 18:
                    return 0b110110; // one, two, many, other
                case 19:
                    return 0b100010; // one, other
                case 20:
                    return 0b111110; // one, two, few, many, other
                case 21:
                    return 0b110010; // one, many, other
                case 22:
                    return 0b100010; // one, other
                case 23:
                    return 0b101000; // few, other
                case 24:
                    return 0b101000; // few, other
            }
            return PluralCategories.OtherOnly;
        }

        /// <summary>Returns the form the cardinal rule set <paramref name="rules"/> chooses for a number.</summary>
        public static PluralCategory SelectCardinal(int rules, in PluralOperands o)
        {
            switch (rules)
            {
                // af, an, asa, az, bal, bem, bez, bg, brx, ce, cgg, chr, ckb, dv, ee, el, eo, eu, fo, fur, gsw, ha,
                // haw, hu, jgo, jmc, ka, kaj, kcg, kk, kkj, kl, ks, ksb, ku, ky, lb, lg, mas, mgo, ml, mn, mr, nah, nb,
                // nd, ne, nn, nnh, no, nr, ny, nyn, om, or, os, pap, ps, rm, rof, rwk, saq, sd, sdh, seh, sn, so, sq,
                // ss, ssy, st, syr, ta, te, teo, tig, tk, tn, tr, ts, ug, uz, ve, vo, vun, wae, xh, xog
                case 1:
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    break;
                // ak, bho, csw, guw, ln, mg, nso, pa, ti, wa
                case 2:
                    if (o.T == 0 && o.I <= 1)
                    {
                        return PluralCategory.One;
                    }
                    break;
                // am, as, bn, doi, fa, gu, hi, kn, kok, kok-Latn, pcm, zu
                case 3:
                    if (o.I == 0 || (o.T == 0 && o.I == 1))
                    {
                        return PluralCategory.One;
                    }
                    break;
                // ar, ars
                case 4:
                    if (o.T == 0 && o.I == 0)
                    {
                        return PluralCategory.Zero;
                    }
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I == 2)
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && o.I % 100 >= 3 && o.I % 100 <= 10)
                    {
                        return PluralCategory.Few;
                    }
                    if (o.T == 0 && o.I % 100 >= 11 && o.I % 100 <= 99)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // ast, de, en, et, fi, fy, gl, ia, ie, io, lij, nl, sc, sv, sw, ur, yi
                case 5:
                    if (o.I == 1 && o.V == 0)
                    {
                        return PluralCategory.One;
                    }
                    break;
                // be
                case 6:
                    if (o.T == 0 && o.I % 10 == 1 && !(o.T == 0 && o.I % 100 == 11))
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I % 10 >= 2 && o.I % 10 <= 4 && !(o.T == 0 && o.I % 100 >= 12 && o.I % 100 <= 14))
                    {
                        return PluralCategory.Few;
                    }
                    if ((o.T == 0 && o.I % 10 == 0) || (o.T == 0 && o.I % 10 >= 5 && o.I % 10 <= 9) || (o.T == 0 && o.I % 100 >= 11 && o.I % 100 <= 14))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // blo, cv, ksh
                case 7:
                    if (o.T == 0 && o.I == 0)
                    {
                        return PluralCategory.Zero;
                    }
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    break;
                // br
                case 8:
                    if (o.T == 0 && o.I % 10 == 1 && !(o.T == 0 && (o.I % 100 == 11 || o.I % 100 == 71 || o.I % 100 == 91)))
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I % 10 == 2 && !(o.T == 0 && (o.I % 100 == 12 || o.I % 100 == 72 || o.I % 100 == 92)))
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && ((o.I % 10 >= 3 && o.I % 10 <= 4) || o.I % 10 == 9) && !(o.T == 0 && ((o.I % 100 >= 10 && o.I % 100 <= 19) || (o.I % 100 >= 70 && o.I % 100 <= 79) || (o.I % 100 >= 90 && o.I % 100 <= 99))))
                    {
                        return PluralCategory.Few;
                    }
                    if (!(o.T == 0 && o.I == 0) && o.T == 0 && o.I % 1000000 == 0)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // bs, hr, sh, sr
                case 9:
                    if ((o.V == 0 && o.I % 10 == 1 && o.I % 100 != 11) || (o.F % 10 == 1 && o.F % 100 != 11))
                    {
                        return PluralCategory.One;
                    }
                    if ((o.V == 0 && o.I % 10 >= 2 && o.I % 10 <= 4 && !(o.I % 100 >= 12 && o.I % 100 <= 14)) || (o.F % 10 >= 2 && o.F % 10 <= 4 && !(o.F % 100 >= 12 && o.F % 100 <= 14)))
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // ca, it, lld, pt-PT, scn, vec
                case 10:
                    if (o.I == 1 && o.V == 0)
                    {
                        return PluralCategory.One;
                    }
                    if ((o.E == 0 && o.I != 0 && o.I % 1000000 == 0 && o.V == 0) || !(o.E <= 5))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // ceb, fil, tl
                case 11:
                    if ((o.V == 0 && (o.I == 1 || o.I == 2 || o.I == 3)) || (o.V == 0 && !(o.I % 10 == 4 || o.I % 10 == 6 || o.I % 10 == 9)) || (o.V != 0 && !(o.F % 10 == 4 || o.F % 10 == 6 || o.F % 10 == 9)))
                    {
                        return PluralCategory.One;
                    }
                    break;
                // cs, sk
                case 12:
                    if (o.I == 1 && o.V == 0)
                    {
                        return PluralCategory.One;
                    }
                    if (o.I >= 2 && o.I <= 4 && o.V == 0)
                    {
                        return PluralCategory.Few;
                    }
                    if (o.V != 0)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // cy
                case 13:
                    if (o.T == 0 && o.I == 0)
                    {
                        return PluralCategory.Zero;
                    }
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I == 2)
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && o.I == 3)
                    {
                        return PluralCategory.Few;
                    }
                    if (o.T == 0 && o.I == 6)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // da
                case 14:
                    if ((o.T == 0 && o.I == 1) || (o.T != 0 && (o.I == 0 || o.I == 1)))
                    {
                        return PluralCategory.One;
                    }
                    break;
                // dsb, hsb
                case 15:
                    if ((o.V == 0 && o.I % 100 == 1) || o.F % 100 == 1)
                    {
                        return PluralCategory.One;
                    }
                    if ((o.V == 0 && o.I % 100 == 2) || o.F % 100 == 2)
                    {
                        return PluralCategory.Two;
                    }
                    if ((o.V == 0 && o.I % 100 >= 3 && o.I % 100 <= 4) || (o.F % 100 >= 3 && o.F % 100 <= 4))
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // es
                case 16:
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if ((o.E == 0 && o.I != 0 && o.I % 1000000 == 0 && o.V == 0) || !(o.E <= 5))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // ff, hy, kab
                case 17:
                    if (o.I == 0 || o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    break;
                // fr
                case 18:
                    if (o.I == 0 || o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if ((o.E == 0 && o.I != 0 && o.I % 1000000 == 0 && o.V == 0) || !(o.E <= 5))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // ga
                case 19:
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I == 2)
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && o.I >= 3 && o.I <= 6)
                    {
                        return PluralCategory.Few;
                    }
                    if (o.T == 0 && o.I >= 7 && o.I <= 10)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // gd
                case 20:
                    if (o.T == 0 && (o.I == 1 || o.I == 11))
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && (o.I == 2 || o.I == 12))
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && ((o.I >= 3 && o.I <= 10) || (o.I >= 13 && o.I <= 19)))
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // gv
                case 21:
                    if (o.V == 0 && o.I % 10 == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.V == 0 && o.I % 10 == 2)
                    {
                        return PluralCategory.Two;
                    }
                    if (o.V == 0 && (o.I % 100 == 0 || o.I % 100 == 20 || o.I % 100 == 40 || o.I % 100 == 60 || o.I % 100 == 80))
                    {
                        return PluralCategory.Few;
                    }
                    if (o.V != 0)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // he
                case 22:
                    if ((o.I == 1 && o.V == 0) || (o.I == 0 && o.V != 0))
                    {
                        return PluralCategory.One;
                    }
                    if (o.I == 2 && o.V == 0)
                    {
                        return PluralCategory.Two;
                    }
                    break;
                // is
                case 23:
                    if ((o.T == 0 && o.I % 10 == 1 && o.I % 100 != 11) || (o.T % 10 == 1 && o.T % 100 != 11))
                    {
                        return PluralCategory.One;
                    }
                    break;
                // iu, naq, sat, se, sma, smi, smj, smn, sms
                case 24:
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I == 2)
                    {
                        return PluralCategory.Two;
                    }
                    break;
                // kw
                case 25:
                    if (o.T == 0 && o.I == 0)
                    {
                        return PluralCategory.Zero;
                    }
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if ((o.T == 0 && (o.I % 100 == 2 || o.I % 100 == 22 || o.I % 100 == 42 || o.I % 100 == 62 || o.I % 100 == 82)) || (o.T == 0 && o.I % 1000 == 0 && o.T == 0 && ((o.I % 100000 >= 1000 && o.I % 100000 <= 20000) || o.I % 100000 == 40000 || o.I % 100000 == 60000 || o.I % 100000 == 80000)) || (!(o.T == 0 && o.I == 0) && o.T == 0 && o.I % 1000000 == 100000))
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && (o.I % 100 == 3 || o.I % 100 == 23 || o.I % 100 == 43 || o.I % 100 == 63 || o.I % 100 == 83))
                    {
                        return PluralCategory.Few;
                    }
                    if (!(o.T == 0 && o.I == 1) && o.T == 0 && (o.I % 100 == 1 || o.I % 100 == 21 || o.I % 100 == 41 || o.I % 100 == 61 || o.I % 100 == 81))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // lag
                case 26:
                    if (o.T == 0 && o.I == 0)
                    {
                        return PluralCategory.Zero;
                    }
                    if ((o.I == 0 || o.I == 1) && !(o.T == 0 && o.I == 0))
                    {
                        return PluralCategory.One;
                    }
                    break;
                // lt
                case 27:
                    if (o.T == 0 && o.I % 10 == 1 && !(o.T == 0 && o.I % 100 >= 11 && o.I % 100 <= 19))
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I % 10 >= 2 && o.I % 10 <= 9 && !(o.T == 0 && o.I % 100 >= 11 && o.I % 100 <= 19))
                    {
                        return PluralCategory.Few;
                    }
                    if (o.F != 0)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // lv, prg
                case 28:
                    if ((o.T == 0 && o.I % 10 == 0) || (o.T == 0 && o.I % 100 >= 11 && o.I % 100 <= 19) || (o.V == 2 && o.F % 100 >= 11 && o.F % 100 <= 19))
                    {
                        return PluralCategory.Zero;
                    }
                    if ((o.T == 0 && o.I % 10 == 1 && !(o.T == 0 && o.I % 100 == 11)) || (o.V == 2 && o.F % 10 == 1 && o.F % 100 != 11) || (o.V != 2 && o.F % 10 == 1))
                    {
                        return PluralCategory.One;
                    }
                    break;
                // mk
                case 29:
                    if ((o.V == 0 && o.I % 10 == 1 && o.I % 100 != 11) || (o.F % 10 == 1 && o.F % 100 != 11))
                    {
                        return PluralCategory.One;
                    }
                    break;
                // mo, ro
                case 30:
                    if (o.I == 1 && o.V == 0)
                    {
                        return PluralCategory.One;
                    }
                    if (o.V != 0 || (o.T == 0 && o.I == 0) || (!(o.T == 0 && o.I == 1) && o.T == 0 && o.I % 100 >= 1 && o.I % 100 <= 19))
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // mt
                case 31:
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I == 2)
                    {
                        return PluralCategory.Two;
                    }
                    if ((o.T == 0 && o.I == 0) || (o.T == 0 && o.I % 100 >= 3 && o.I % 100 <= 10))
                    {
                        return PluralCategory.Few;
                    }
                    if (o.T == 0 && o.I % 100 >= 11 && o.I % 100 <= 19)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // pl
                case 32:
                    if (o.I == 1 && o.V == 0)
                    {
                        return PluralCategory.One;
                    }
                    if (o.V == 0 && o.I % 10 >= 2 && o.I % 10 <= 4 && !(o.I % 100 >= 12 && o.I % 100 <= 14))
                    {
                        return PluralCategory.Few;
                    }
                    if ((o.V == 0 && o.I != 1 && o.I % 10 <= 1) || (o.V == 0 && o.I % 10 >= 5 && o.I % 10 <= 9) || (o.V == 0 && o.I % 100 >= 12 && o.I % 100 <= 14))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // pt
                case 33:
                    if (o.I <= 1)
                    {
                        return PluralCategory.One;
                    }
                    if ((o.E == 0 && o.I != 0 && o.I % 1000000 == 0 && o.V == 0) || !(o.E <= 5))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // ru, uk
                case 34:
                    if (o.V == 0 && o.I % 10 == 1 && o.I % 100 != 11)
                    {
                        return PluralCategory.One;
                    }
                    if (o.V == 0 && o.I % 10 >= 2 && o.I % 10 <= 4 && !(o.I % 100 >= 12 && o.I % 100 <= 14))
                    {
                        return PluralCategory.Few;
                    }
                    if ((o.V == 0 && o.I % 10 == 0) || (o.V == 0 && o.I % 10 >= 5 && o.I % 10 <= 9) || (o.V == 0 && o.I % 100 >= 11 && o.I % 100 <= 14))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // sgs
                case 35:
                    if (o.T == 0 && o.I % 10 == 1 && !(o.T == 0 && o.I % 100 == 11))
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I == 2)
                    {
                        return PluralCategory.Two;
                    }
                    if (!(o.T == 0 && o.I == 2) && o.T == 0 && o.I % 10 >= 2 && o.I % 10 <= 9 && !(o.T == 0 && o.I % 100 >= 11 && o.I % 100 <= 19))
                    {
                        return PluralCategory.Few;
                    }
                    if (o.F != 0)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // shi
                case 36:
                    if (o.I == 0 || (o.T == 0 && o.I == 1))
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I >= 2 && o.I <= 10)
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // si
                case 37:
                    if ((o.T == 0 && (o.I == 0 || o.I == 1)) || (o.I == 0 && o.F == 1))
                    {
                        return PluralCategory.One;
                    }
                    break;
                // sl
                case 38:
                    if (o.V == 0 && o.I % 100 == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.V == 0 && o.I % 100 == 2)
                    {
                        return PluralCategory.Two;
                    }
                    if ((o.V == 0 && o.I % 100 >= 3 && o.I % 100 <= 4) || o.V != 0)
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // tzm
                case 39:
                    if ((o.T == 0 && o.I <= 1) || (o.T == 0 && o.I >= 11 && o.I <= 99))
                    {
                        return PluralCategory.One;
                    }
                    break;
            }
            return PluralCategory.Other;
        }

        /// <summary>Returns the form the ordinal rule set <paramref name="rules"/> chooses for a number.</summary>
        public static PluralCategory SelectOrdinal(int rules, in PluralOperands o)
        {
            switch (rules)
            {
                // as, bn
                case 1:
                    if (o.T == 0 && (o.I == 1 || o.I == 5 || o.I == 7 || o.I == 8 || o.I == 9 || o.I == 10))
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && (o.I == 2 || o.I == 3))
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && o.I == 4)
                    {
                        return PluralCategory.Few;
                    }
                    if (o.T == 0 && o.I == 6)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // az
                case 2:
                    if (o.I % 10 == 1 || o.I % 10 == 2 || o.I % 10 == 5 || o.I % 10 == 7 || o.I % 10 == 8 || o.I % 100 == 20 || o.I % 100 == 50 || o.I % 100 == 70 || o.I % 100 == 80)
                    {
                        return PluralCategory.One;
                    }
                    if (o.I % 10 == 3 || o.I % 10 == 4 || o.I % 1000 == 100 || o.I % 1000 == 200 || o.I % 1000 == 300 || o.I % 1000 == 400 || o.I % 1000 == 500 || o.I % 1000 == 600 || o.I % 1000 == 700 || o.I % 1000 == 800 || o.I % 1000 == 900)
                    {
                        return PluralCategory.Few;
                    }
                    if (o.I == 0 || o.I % 10 == 6 || o.I % 100 == 40 || o.I % 100 == 60 || o.I % 100 == 90)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // bal, fil, fr, ga, hy, lo, mo, ms, ro, tl, vi
                case 3:
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    break;
                // be
                case 4:
                    if (o.T == 0 && (o.I % 10 == 2 || o.I % 10 == 3) && !(o.T == 0 && (o.I % 100 == 12 || o.I % 100 == 13)))
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // blo
                case 5:
                    if (o.I == 0)
                    {
                        return PluralCategory.Zero;
                    }
                    if (o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.I == 2 || o.I == 3 || o.I == 4 || o.I == 5 || o.I == 6)
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // ca
                case 6:
                    if (o.T == 0 && (o.I == 1 || o.I == 3))
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I == 2)
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && o.I == 4)
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // cy
                case 7:
                    if (o.T == 0 && (o.I == 0 || o.I == 7 || o.I == 8 || o.I == 9))
                    {
                        return PluralCategory.Zero;
                    }
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I == 2)
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && (o.I == 3 || o.I == 4))
                    {
                        return PluralCategory.Few;
                    }
                    if (o.T == 0 && (o.I == 5 || o.I == 6))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // en
                case 8:
                    if (o.T == 0 && o.I % 10 == 1 && !(o.T == 0 && o.I % 100 == 11))
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I % 10 == 2 && !(o.T == 0 && o.I % 100 == 12))
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && o.I % 10 == 3 && !(o.T == 0 && o.I % 100 == 13))
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // gd
                case 9:
                    if (o.T == 0 && (o.I == 1 || o.I == 11))
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && (o.I == 2 || o.I == 12))
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && (o.I == 3 || o.I == 13))
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // gu, hi
                case 10:
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && (o.I == 2 || o.I == 3))
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && o.I == 4)
                    {
                        return PluralCategory.Few;
                    }
                    if (o.T == 0 && o.I == 6)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // hu
                case 11:
                    if (o.T == 0 && (o.I == 1 || o.I == 5))
                    {
                        return PluralCategory.One;
                    }
                    break;
                // it, lld, sc, vec
                case 12:
                    if (o.T == 0 && (o.I == 11 || o.I == 8 || o.I == 80 || o.I == 800))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // ka
                case 13:
                    if (o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.I == 0 || (o.I % 100 >= 2 && o.I % 100 <= 20) || o.I % 100 == 40 || o.I % 100 == 60 || o.I % 100 == 80)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // kk
                case 14:
                    if ((o.T == 0 && o.I % 10 == 6) || (o.T == 0 && o.I % 10 == 9) || (o.T == 0 && o.I % 10 == 0 && !(o.T == 0 && o.I == 0)))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // kok, kok-Latn, mr
                case 15:
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && (o.I == 2 || o.I == 3))
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && o.I == 4)
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // kw
                case 16:
                    if ((o.T == 0 && o.I >= 1 && o.I <= 4) || (o.T == 0 && ((o.I % 100 >= 1 && o.I % 100 <= 4) || (o.I % 100 >= 21 && o.I % 100 <= 24) || (o.I % 100 >= 41 && o.I % 100 <= 44) || (o.I % 100 >= 61 && o.I % 100 <= 64) || (o.I % 100 >= 81 && o.I % 100 <= 84))))
                    {
                        return PluralCategory.One;
                    }
                    if ((o.T == 0 && o.I == 5) || (o.T == 0 && o.I % 100 == 5))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // lij, scn
                case 17:
                    if (o.T == 0 && (o.I == 11 || o.I == 8 || (o.I >= 80 && o.I <= 89) || (o.I >= 800 && o.I <= 899)))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // mk
                case 18:
                    if (o.I % 10 == 1 && o.I % 100 != 11)
                    {
                        return PluralCategory.One;
                    }
                    if (o.I % 10 == 2 && o.I % 100 != 12)
                    {
                        return PluralCategory.Two;
                    }
                    if ((o.I % 10 == 7 || o.I % 10 == 8) && !(o.I % 100 == 17 || o.I % 100 == 18))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // ne
                case 19:
                    if (o.T == 0 && o.I >= 1 && o.I <= 4)
                    {
                        return PluralCategory.One;
                    }
                    break;
                // or
                case 20:
                    if (o.T == 0 && (o.I == 1 || o.I == 5 || (o.I >= 7 && o.I <= 9)))
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && (o.I == 2 || o.I == 3))
                    {
                        return PluralCategory.Two;
                    }
                    if (o.T == 0 && o.I == 4)
                    {
                        return PluralCategory.Few;
                    }
                    if (o.T == 0 && o.I == 6)
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // sq
                case 21:
                    if (o.T == 0 && o.I == 1)
                    {
                        return PluralCategory.One;
                    }
                    if (o.T == 0 && o.I % 10 == 4 && !(o.T == 0 && o.I % 100 == 14))
                    {
                        return PluralCategory.Many;
                    }
                    break;
                // sv
                case 22:
                    if (o.T == 0 && (o.I % 10 == 1 || o.I % 10 == 2) && !(o.T == 0 && (o.I % 100 == 11 || o.I % 100 == 12)))
                    {
                        return PluralCategory.One;
                    }
                    break;
                // tk
                case 23:
                    if ((o.T == 0 && (o.I % 10 == 6 || o.I % 10 == 9)) || (o.T == 0 && o.I == 10))
                    {
                        return PluralCategory.Few;
                    }
                    break;
                // uk
                case 24:
                    if (o.T == 0 && o.I % 10 == 3 && !(o.T == 0 && o.I % 100 == 13))
                    {
                        return PluralCategory.Few;
                    }
                    break;
            }
            return PluralCategory.Other;
        }

        private static int Find(string[] locales, byte[] sets, string locale)
        {
            int index = global::System.Array.BinarySearch(locales, locale, global::System.StringComparer.Ordinal);
            return index >= 0 ? sets[index] : -1;
        }
    }
}
