using NUnit.Framework;
using reromanlee.ReactiveLocalizer.Authoring;
using System.Collections.Generic;

namespace reromanlee.ReactiveLocalizer.Tests
{
    public class KeysScriptWriterTests
    {
        private const string Expected =
            "//------------------------------------------------------------------------------\n" +
            "// <auto-generated>\n" +
            "//     Generated by ReactiveLocalizer from the catalog 'Localization'. It changes\n" +
            "//     when a key, alias, argument, table or language changes, never when only a text does.\n" +
            "//     Edits here are lost: edit the catalog and its .lang files instead.\n" +
            "// </auto-generated>\n" +
            "//------------------------------------------------------------------------------\n" +
            "\n" +
            "#pragma warning disable 1591\n" +
            "\n" +
            "namespace MyGame\n" +
            "{\n" +
            "    /// <summary>\n" +
            "    /// The tables and entries of the catalog 'Localization', as keys the compiler checks.\n" +
            "    /// </summary>\n" +
            "    public static class LocalizationKeys\n" +
            "    {\n" +
            "        /// <summary>The catalog itself, for <c>new Localizer(LocalizationKeys.CatalogKey, host)</c>.</summary>\n" +
            "        public static readonly global::reromanlee.ReactiveLocalizer.CatalogKey CatalogKey = new(\"Localization\");\n" +
            "\n" +
            "        /// <summary>The entries of the table 'Common'.</summary>\n" +
            "        public static class Common\n" +
            "        {\n" +
            "            /// <summary>The table itself.</summary>\n" +
            "            public static readonly global::reromanlee.ReactiveLocalizer.TableKey TableKey = new(\"Common\");\n" +
            "\n" +
            "            public static readonly global::reromanlee.ReactiveLocalizer.EntryKey @class = new(TableKey, \"class\");\n" +
            "            public static readonly global::reromanlee.ReactiveLocalizer.EntryKey Confirm = new(TableKey, \"Confirm\");\n" +
            "        }\n" +
            "\n" +
            "        /// <summary>The entries of the table 'Shop'.</summary>\n" +
            "        public static class Shop\n" +
            "        {\n" +
            "            /// <summary>The table itself.</summary>\n" +
            "            public static readonly global::reromanlee.ReactiveLocalizer.TableKey TableKey = new(\"Shop\");\n" +
            "\n" +
            "            public static readonly global::reromanlee.ReactiveLocalizer.EntryKey Purchase = new(TableKey, \"Purchase\");\n" +
            "            public static readonly global::reromanlee.ReactiveLocalizer.EntryKey Title = new(TableKey, \"Title\");\n" +
            "\n" +
            "            public static global::reromanlee.ReactiveLocalizer.EntryMessage CoinBalance(global::reromanlee.ReactiveLocalizer.MessageNumber coins) =>\n" +
            "                new(_CoinBalance, new global::reromanlee.ReactiveLocalizer.MessageArgument(\"coins\", coins));\n" +
            "\n" +
            "            public static global::reromanlee.ReactiveLocalizer.EntryMessage Gift(global::reromanlee.ReactiveLocalizer.MessageNumber coins, string gender, global::reromanlee.ReactiveLocalizer.MessageValue name) =>\n" +
            "                new(_Gift, new global::reromanlee.ReactiveLocalizer.MessageArgument(\"coins\", coins), new global::reromanlee.ReactiveLocalizer.MessageArgument(\"gender\", gender), new global::reromanlee.ReactiveLocalizer.MessageArgument(\"name\", name));\n" +
            "\n" +
            "            [global::System.Obsolete(\"Renamed to Purchase.\")]\n" +
            "            public static readonly global::reromanlee.ReactiveLocalizer.EntryKey BuyButton = Purchase;\n" +
            "\n" +
            "            [global::System.Obsolete(\"Renamed to CoinBalance.\")]\n" +
            "            public static global::reromanlee.ReactiveLocalizer.EntryMessage CoinsLabel(global::reromanlee.ReactiveLocalizer.MessageNumber coins) =>\n" +
            "                CoinBalance(coins);\n" +
            "\n" +
            "            private static readonly global::reromanlee.ReactiveLocalizer.EntryKey _CoinBalance = new(TableKey, \"CoinBalance\");\n" +
            "            private static readonly global::reromanlee.ReactiveLocalizer.EntryKey _Gift = new(TableKey, \"Gift\");\n" +
            "        }\n" +
            "    }\n" +
            "\n" +
            "    /// <summary>\n" +
            "    /// The languages of the catalog 'Localization'.\n" +
            "    /// </summary>\n" +
            "    public static class LocalizationLanguages\n" +
            "    {\n" +
            "        public static readonly global::reromanlee.ReactiveLocalizer.LanguageKey English = new(\"English\");\n" +
            "        public static readonly global::reromanlee.ReactiveLocalizer.LanguageKey Russian = new(\"Russian\");\n" +
            "    }\n" +
            "}\n";

        [Test]
        public void Write_GeneratesSortedKeysAliasesAndLanguages()
        {
            KeysScript script = new("Localization", "MyGame", new[] { "Russian", "English" }, new[]
            {
                new KeysScriptTable("Shop", new[]
                {
                    new KeysScriptEntry("Title"),
                    new KeysScriptEntry("Purchase"),
                    KeysScriptEntry.FromSource("Gift", "{name} sent {gender, select, female {her} other {their}} {coins, number} coins"),
                    KeysScriptEntry.FromSource("CoinBalance", "You have {coins, plural, one {# coin} other {# coins}}.")
                }, new[]
                {
                    new KeyValuePair<string, string>("CoinsLabel", "CoinBalance"),
                    new KeyValuePair<string, string>("BuyButton", "Purchase")
                }),
                new KeysScriptTable("Common", new[] { "Confirm", "class" }, null)
            });
            List<string> problems = new();

            string source = KeysScriptWriter.Write(script, problems);

            Assert.That(source, Is.EqualTo(Expected));
            Assert.That(problems, Is.Empty);
            Assert.That(script.FileName, Is.EqualTo("LocalizationKeys.cs"));
        }

        [Test]
        public void FromSource_SortsArgumentsAndKeepsBrokenMessagesPlain()
        {
            KeysScriptEntry message = KeysScriptEntry.FromSource("Trade", "{seller} sells {Item} for {price, number}");
            KeysScriptEntry broken = KeysScriptEntry.FromSource("Broken", "{count, plural, one {#}}");
            KeysScriptEntry plain = KeysScriptEntry.FromSource("Plain", "Don't '{'panic'}'");

            Assert.That(message.Arguments.Count, Is.EqualTo(3));
            Assert.That(message.Arguments[0].Name, Is.EqualTo("Item"));
            Assert.That(message.Arguments[1].Name, Is.EqualTo("price"));
            Assert.That(message.Arguments[1].Kind, Is.EqualTo(MessageArgumentKind.Number));
            Assert.That(message.Arguments[2].Name, Is.EqualTo("seller"));
            Assert.That(broken.HasArguments, Is.False);
            Assert.That(plain.HasArguments, Is.False);
        }

        [Test]
        public void Write_UsesTheGlobalNamespaceWithoutOne()
        {
            string source = KeysScriptWriter.Write(new KeysScript("Localization", null, new[] { "English" }, null), null);

            Assert.That(source, Does.Contain("\npublic static class LocalizationKeys\n"));
            Assert.That(source, Does.Not.Contain("namespace"));
        }

        [Test]
        public void Write_LeavesOutNamesThatWouldNotCompileAndSaysWhy()
        {
            KeysScript script = new("Localization", "My Game", new[] { "English", "LocalizationLanguages" }, new[]
            {
                new KeysScriptTable("Inventory", new[] { "Inventory", "TableKey", "Sword" }, new[]
                {
                    new KeyValuePair<string, string>("Blade", "Missing"),
                    new KeyValuePair<string, string>("Sword", "Sword")
                }),
                new KeysScriptTable("CatalogKey", new[] { "Anything" }, null)
            });
            List<string> problems = new();

            string source = KeysScriptWriter.Write(script, problems);

            Assert.That(problems.Count, Is.EqualTo(7));
            Assert.That(source, Does.Contain("EntryKey Sword = new(TableKey, \"Sword\");"));
            Assert.That(source, Does.Not.Contain("Inventory = new"));
            Assert.That(source, Does.Not.Contain("Blade"));
            Assert.That(source, Does.Not.Contain("class CatalogKey"));
            Assert.That(source, Does.Not.Contain("namespace"));
        }
    }
}
