//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by ReactiveLocalizer from the catalog 'QuickStart'. It changes
//     when a key, alias, argument, table or language changes, never when only a text does.
//     Edits here are lost: edit the catalog and its .lang files instead.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace reromanlee.ReactiveLocalizer.Samples.QuickStart
{
    /// <summary>
    /// The tables and entries of the catalog 'QuickStart', as keys the compiler checks.
    /// </summary>
    public static class QuickStartKeys
    {
        /// <summary>The catalog itself, for <c>new Localizer(QuickStartKeys.CatalogKey, host)</c>.</summary>
        public static readonly global::reromanlee.ReactiveLocalizer.CatalogKey CatalogKey = new("QuickStart");

        /// <summary>The entries of the table 'Demo'.</summary>
        public static class Demo
        {
            /// <summary>The table itself.</summary>
            public static readonly global::reromanlee.ReactiveLocalizer.TableKey TableKey = new("Demo");

            public static readonly global::reromanlee.ReactiveLocalizer.EntryKey AddCoin = new(TableKey, "AddCoin");
            public static readonly global::reromanlee.ReactiveLocalizer.EntryKey Greeting = new(TableKey, "Greeting");
            public static readonly global::reromanlee.ReactiveLocalizer.EntryKey Hint = new(TableKey, "Hint");
            public static readonly global::reromanlee.ReactiveLocalizer.EntryKey Title = new(TableKey, "Title");

            public static global::reromanlee.ReactiveLocalizer.EntryMessage Coins(global::reromanlee.ReactiveLocalizer.MessageNumber coins) =>
                new(_Coins, new global::reromanlee.ReactiveLocalizer.MessageArgument("coins", coins));

            private static readonly global::reromanlee.ReactiveLocalizer.EntryKey _Coins = new(TableKey, "Coins");
        }
    }

    /// <summary>
    /// The languages of the catalog 'QuickStart'.
    /// </summary>
    public static class QuickStartLanguages
    {
        public static readonly global::reromanlee.ReactiveLocalizer.LanguageKey English = new("English");
        public static readonly global::reromanlee.ReactiveLocalizer.LanguageKey Pirate = new("Pirate");
        public static readonly global::reromanlee.ReactiveLocalizer.LanguageKey Russian = new("Russian");
    }
}
